"""Configuration for the Pololu Balboa 32U4 (``assets/data/balboa/balboa.urdf``).

Every physical constant of the project lives here; sources and the list of assumptions are in ``guide/01_robot.md``.
Formulas: ``guide/03_dynamics.md`` (motor and plant), ``guide/02_sensing.md`` (IMU).

The URDF is generated from the Pololu CAD by ``tools/build_balboa_urdf.py`` (which reads the masses below). Frame:
x forward, y left, z up, origin on the wheel axle, posed at the equilibrium where the centre of mass is straight above
it. Articulation root ``base_link``, revolute joints ``left_wheel_joint`` and ``right_wheel_joint`` (axis +y, so equal
positive joint speeds drive straight forward).
"""

import json
import math

import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg
from isaaclab.assets import ArticulationCfg
from isaaclab_physx.sim.schemas import PhysxArticulationCfg, PhysxRigidBodyCfg

from Balance_Car_RL.assets import BALANCE_CAR_RL_ASSETS_DIR

_CAR_URDF_PATH = str(BALANCE_CAR_RL_ASSETS_DIR / "balboa" / "balboa.urdf")

# ── Geometry ────────────────────────────────────────────────────────────────────────────
WHEEL_RADIUS_M = 0.040
"""Pololu 80x10 mm wheel (user's guide, kit dimension drawing): 80 mm diameter. The URDF origin sits on the axle, so
this is also the spawn height."""

# ── Mass ────────────────────────────────────────────────────────────────────────────────
BASE_MASS_KG = 0.27
"""Chassis, control board, six AA cells and two gearmotors [kg]. Not published: a nominal estimate, spread over the CAD
volumes to place the centre of mass (19.9 mm above the axle). Weigh the real robot (``guide/01_robot.md``)."""

WHEEL_MASS_KG = 0.020
"""One Pololu 80x10 mm wheel with its hub [kg]. Not published: a nominal estimate."""

# ── Motor and gearbox ───────────────────────────────────────────────────────────────────
# 50:1 HPCB 6 V micro metal gearmotor behind the 49:17 gearbox of the Balboa chassis (Pololu user's guide recommends
# the 30:1, 50:1 or 75:1 HPCB versions). Datasheet row of the HPCB 6 V comparison table: 650 rpm and 0.74 kg cm at 6 V.
GEARMOTOR_RATIO = 3344 / 65
"""Exact ratio of the 50:1 gearmotor (Pololu Balboa gear ratio chart)."""

EXTERNAL_RATIO = 49 / 17
"""49:17 gearbox of the chassis (2.88:1 reduction), one of five options from 1.64:1 to 2.88:1."""

TOTAL_RATIO = GEARMOTOR_RATIO * EXTERNAL_RATIO
"""Motor shaft turns per wheel turn (148.3:1, chart)."""

_KGCM_TO_NM = 0.0980665

WHEEL_STALL_TORQUE_NM = 0.74 * _KGCM_TO_NM * EXTERNAL_RATIO
"""Stall torque at the wheel [N m]: 0.74 kg cm (50:1 HPCB 6 V at 6 V) times the external reduction, 100 % efficient."""

WHEEL_NO_LOAD_SPEED_RAD_S = 650.0 * 2.0 * math.pi / 60.0 / EXTERNAL_RATIO
"""No-load wheel speed [rad/s]: 650 rpm at the gearmotor output divided by the external reduction."""

MOTOR_ROTOR_INERTIA = 7.0e-9
"""Rotor inertia of the micro metal motor [kg m^2]. Not published by Pololu: an estimate (about 1.5 g, 6 mm)."""

WHEEL_ARMATURE = MOTOR_ROTOR_INERTIA * TOTAL_RATIO**2
"""Rotor inertia reflected to the wheel [kg m^2] (1.54e-4), added to the joint inertia."""

# ── IMU ─────────────────────────────────────────────────────────────────────────────────
# The Balboa control board carries an ST LSM6DS33 (accelerometer and gyroscope). Datasheet (Table 3, FS = ±2 g,
# ODR = 104 Hz): rate noise density 7 mdps/sqrt(Hz), acceleration noise density 90 ug/sqrt(Hz), typical zero-g level
# offset ±40 mg, typical zero-rate level ±10 dps.
_IMU_MOUNT = json.loads((BALANCE_CAR_RL_ASSETS_DIR / "balboa" / "imu_mount.json").read_text())

IMU_POS_M = tuple(_IMU_MOUNT["position_m"])
"""IMU position in the car frame [m]: centre of the control board (assumption: the chip sits at the board centre)."""

IMU_QUAT_XYZW = tuple(_IMU_MOUNT["quat_xyzw"])
"""IMU frame orientation in the car frame, quaternion (x, y, z, w). The IMU axes are the board axes, tilted with the
chassis, so they are not the car axes (generated by ``tools/build_balboa_urdf.py``)."""

IMU_R_CAR_FROM_IMU = tuple(tuple(row) for row in _IMU_MOUNT["rotation_car_from_imu"])
"""Rotation matrix with ``v_car = R @ v_imu``. Assumes the mounting is known (calibrated)."""

IMU_BANDWIDTH_HZ = 52.0
"""Noise bandwidth [Hz]: half the 104 Hz output data rate of the datasheet noise figures."""

IMU_ACCEL_NOISE_STD = 90e-6 * 9.80665 * math.sqrt(IMU_BANDWIDTH_HZ)
"""Accelerometer noise per sample and axis [m/s^2]: noise density x sqrt(bandwidth), 6.4e-3."""

IMU_GYRO_NOISE_STD = math.radians(7e-3) * math.sqrt(IMU_BANDWIDTH_HZ)
"""Gyroscope noise per sample and axis [rad/s]: noise density x sqrt(bandwidth), 8.8e-4."""

IMU_CALIBRATION_RESIDUAL = 0.1
"""Share of the datasheet zero-g and zero-rate offsets left after a static calibration at start-up. An assumption:
the datasheet values are for an uncalibrated part, and the Balboa firmware calibrates the gyro at boot."""

IMU_ACCEL_BIAS_MAX = IMU_CALIBRATION_RESIDUAL * 0.040 * 9.80665
"""Accelerometer offset range per axis [m/s^2], uniform per episode: 10 % of ±40 mg."""

IMU_GYRO_BIAS_MAX = IMU_CALIBRATION_RESIDUAL * math.radians(10.0)
"""Gyroscope offset range per axis [rad/s], uniform per episode: 10 % of ±10 dps."""

GRAVITY_FILTER_TAU_S = 1.0
"""Time constant [s] of the complementary filter: the gyro dominates faster motion, the accelerometer corrects slower
drift. The gyro weight per step is ``tau / (tau + dt)`` (0.98 at 50 Hz), so simulation and robot agree at any rate."""

ACCEL_COMP_TAU_S = 0.05
"""Time constant [s] of the low-pass on the axle acceleration that is removed from the accelerometer. The acceleration
is the difference of the encoder-based speed, which is noisy, so it is smoothed."""

# ── Articulation ────────────────────────────────────────────────────────────────────────
CAR_CFG = ArticulationCfg(
    prim_path="{ENV_REGEX_NS}/Robot",
    spawn=sim_utils.UrdfFileCfg(
        asset_path=_CAR_URDF_PATH,
        fix_base=False,
        merge_fixed_joints=True,
        make_instanceable=False,
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=None, damping=None)
        ),
        rigid_props=[
            sim_utils.UsdPhysicsRigidBodyCfg(rigid_body_enabled=True),
            PhysxRigidBodyCfg(max_depenetration_velocity=1.0),
        ],
        articulation_props=[
            PhysxArticulationCfg(
                enabled_self_collisions=False,
                solver_position_iteration_count=8,
                solver_velocity_iteration_count=1,
            ),
        ],
    ),
    init_state=ArticulationCfg.InitialStateCfg(pos=(0.0, 0.0, WHEEL_RADIUS_M + 0.001)),
    actuators={
        # Torque-controlled wheels: the policy outputs torque, like a current-controlled motor driver.
        # DCMotor clips it with the torque-speed line of the real motor (stall torque at rest, zero at no-load speed).
        "wheels": DCMotorCfg(
            joint_names_expr=[".*_wheel_joint"],
            saturation_effort=WHEEL_STALL_TORQUE_NM,
            actuator_effort_limit=WHEEL_STALL_TORQUE_NM,
            actuator_velocity_limit=WHEEL_NO_LOAD_SPEED_RAD_S,
            stiffness=0.0,
            damping=0.0,
            armature=WHEEL_ARMATURE,
        ),
    },
)
"""Balboa balancing robot: the wheels are the only actuated joints, the body is a free-floating base."""
